# Generated by Django 5.0.1 on 2024-02-01 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('profile_photo', models.ImageField(default='profile_photos/default.jpeg', upload_to='profile_photos/')),
                ('bio', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Techno', 'Techno'), ('Hardgroove', 'Hardgroove'), ('Disco', 'Disco'), ('Nu-Disco', 'Nu-Disco'), ('Funk', 'Funk'), ('House', 'House')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(upload_to='tracks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('track_photo', models.ImageField(default='track_photos/default.jpeg', upload_to='track_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('artists', models.ManyToManyField(related_name='tracks', to='music.artist')),
                ('tags', models.ManyToManyField(to='music.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi', 'mov'])])),
                ('video_photo', models.ImageField(default='video_photos/default.jpeg', upload_to='video_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('artists', models.ManyToManyField(related_name='videos', to='music.artist')),
                ('tags', models.ManyToManyField(to='music.tag')),
            ],
        ),
    ]
