# Generated by Django 4.2.9 on 2024-01-23 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_alter_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='users',
            field=models.ManyToManyField(related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='users',
            field=models.ManyToManyField(related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
