# Generated by Django 5.0.1 on 2024-02-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_artist_bio_alter_track_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('SoundCloud', 'SoundCloud'), ('Mixcloud', 'Mixcloud'), ('TikTok', 'TikTok'), ('Twitch', 'Twitch'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
    ]
