# Generated by Django 5.0.1 on 2024-01-27 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_users_alter_video_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_photo',
            field=models.ImageField(default='video_photos/default.jpeg', upload_to='video_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
