# Generated by Django 5.0.1 on 2024-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_video_video_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('profile_photo', models.ImageField(default='profile_photos/default.jpeg', upload_to='profile_photos/')),
                ('bio', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', to='music.artist'),
        ),
        migrations.AddField(
            model_name='video',
            name='artists',
            field=models.ManyToManyField(related_name='videos', to='music.artist'),
        ),
    ]
