# Generated by Django 5.0.1 on 2024-02-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_socialmedia_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='music.artist'),
        ),
    ]
