# Generated by Django 5.0.1 on 2024-02-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_socialmedia_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='handle',
        ),
    ]
