# Generated by Django 5.0.1 on 2024-01-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_artist_track_artists_video_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='users',
        ),
        migrations.RemoveField(
            model_name='video',
            name='users',
        ),
    ]
