# Generated by Django 5.0.1 on 2024-02-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_socialmedia_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'instagram'), ('SoundCloud', 'soundloud'), ('Mixcloud', 'mixcloud'), ('TikTok', 'tiktok'), ('Twitch', 'twitch'), ('Facebook', 'facebook'), ('Twitter', 'twitter')], max_length=255),
        ),
    ]
