# Generated by Django 5.0.1 on 2024-02-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'instagram'), ('SoundCloud', 'soundloud'), ('Mixloud', 'mixcloud'), ('TikTok', 'tiktok'), ('Twitch', 'twitch'), ('Facebook', 'facebook'), ('Twitter', 'twitter')], max_length=255),
        ),
    ]
