# Generated by Django 5.0.1 on 2024-02-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('soundloud', 'SoundCloud'), ('mixcloud', 'Mixcloud'), ('tiktok', 'TikTok'), ('twitch', 'Twitch'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=255),
        ),
    ]
