# Generated by Django 5.0.1 on 2024-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, default='Illi e Tellure dj sunt, qui per musicos et rhythmos suos gaudium diffundere amant. Musicam vident extensionem sui et medium connectendi cum aliis. Superbiam esse partem Multiplex Expressios suinus.', null=True),
        ),
    ]
