# Generated by Django 5.0.1 on 2024-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, default="Artifex, qui credit musicam esse extensionem animae et medium connexionis cum aliis. Gaudium toto orbe diffundunt suis musicis et rhythmis. Superbum esse partem 'Multiplici Expressionum' quadrigis.", null=True),
        ),
    ]
