# Generated by Django 5.0.1 on 2024-02-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_alter_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default_profile_photo.jpeg', upload_to='profile_photos/'),
        ),
    ]
