# Generated by Django 5.0.1 on 2024-02-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_artist_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default.jpeg', upload_to='profile_photos/'),
        ),
    ]
