# Generated by Django 5.0.1 on 2024-03-04 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_alter_artist_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_photo',
            field=models.ImageField(default='track_photos/default.jpeg', upload_to='track_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'avif'])]),
        ),
    ]
