# Generated by Django 5.0.1 on 2024-03-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_alter_track_track_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_photo',
            field=models.ImageField(default='track_photos/default.jpeg', upload_to='track_photos/'),
        ),
    ]
