# Generated by Django 5.0.1 on 2024-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_track_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='listens',
            field=models.IntegerField(default=0),
        ),
    ]
